spring.application.name=Gestion_de_pedidos_API

# Datos de conexión a MySQL
spring.datasource.url=${DB_URL}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Configuración de JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true

# SQL
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# Habilitar api-docs y swagger-ui
springdoc.api-docs.enable=true
springdoc.swagger-ui.enable=true

# Url o ruta de swagger-ui
springdoc.swagger-ui.path=/doc/swagger-ui.html